language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm

script:
  - mkdir -p build/logs
  - php vendor/bin/simple-phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls -v
